### ISSUE TITLE
Song-index page

### ISSUE THREAD

**Issue by thomasdilts** [thomasdilts/churchsongs#1]
1. Add musik/text/copyright selection before the author.
2. Add search for the author as well as search for the tag

**Comment by Malekb32** [comment]
![09](https://user-images.githubusercontent.com/126695454/232487888-0c28c5a7-5e99-4b25-a723-548b2cd5484b.JPG)
I think something similar to the picture would work. Like having them as 3-4 dropdown menu with search function.

**Comment by thomasdilts** [comment]
I think this is finished now. It is not as you desiged but as I have designed. I think we should close this now
