### ISSUE TITLE
web GUI design for sets

### ISSUE THREAD

**Issue by thomasdilts** [thomasdilts/churchsongs#100]
Need a design for the web GUI for sets.

**Comment by MalekBakary** [comment]
I can fix it as soon as I understand what it means exactly 😅

**Comment by MalekBakary** [comment]
Forget it, GUI means graphical user interface. 
I will do it soon

**Comment by MalekBakary** [comment]
You can find the sets and sets order design in Figma now.
To help you read my mind, please see the comments in the image below.
Feel free to close this issue if you get all the info that you need. 
![24](https://github.com/thomasdilts/churchsongs/assets/126695454/abacab20-994a-46ef-9fbf-ea892082f939)

**Comment by thomasdilts** [comment]
Ok. I'm done now. You may think I've gone blind because I obviously couldn't see your design.  But I did follow, that is, my way.  The list is DragAndDrop as you have longed for. BUT drag and drop doesn't work on touch screens. It's only for desktops. So I also have icons for up and down for the touch screens.

**Comment by MalekBakary** [comment]
What are you talking about!!! it is amazing... THANK YOU!! I love it.
It only needs some CSS and it will be done

**Comment by MalekBakary** [comment]
For some reason the drag and drop has never worked for me not on Chrome or Opera neither. Is it a problem from my end?
