### ISSUE TITLE
Tag and Author APIs need authorization! 

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#101]
We made the library with all its feature without login.
but we need to make the [Author](https://github.com/thomasdilts/churchsongs/wiki/Author-get) and [Tag](https://github.com/thomasdilts/churchsongs/wiki/Tag-get) APIs without authorization too.

**Comment by thomasdilts** [comment]
This is only for the Tag Get API and the Author Get api
