### ISSUE TITLE
Signup API resend verification email

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#103]
I don't have the option to resend the verification email.
can we add it to [Signup API](https://github.com/thomasdilts/churchsongs/wiki/Signup) as an optional parameter?

**Comment by MalekBakary** [comment]
This one is related to the change email option. If you remember @thomasdilts you would make it a requirement to re-verify if anyone change the mail

**Comment by thomasdilts** [comment]
@MalekBakary what you are talking about is not at all the same as what @eliasalbro95 is talking about in the original request. Two completely different things. No relation whatsoever. I'm going to do what @eliasalbro95 asked for and if you want your thing as well then please open another issue and prioritize it.

**Comment by thomasdilts** [comment]
Done. See https://github.com/thomasdilts/churchsongs/wiki/Resend-verify
