### ISSUE TITLE
Profile alt picture doesn't change when the song role changed

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#104]
it should be changed when the user changes his song role coz I using the same alt picture if the user doesn't upload his profile picture.

**Comment by thomasdilts** [comment]
It changes immediately for me.  Maybe you forgot to hit the save button

**Comment by thomasdilts** [comment]
I tried your app. There the photo doesn't change but that's a bug in your app. The API returns the correct photo

**Comment by eliasalbro95** [comment]
Hi Thomas,
I just tried the same on the website, but it is still the same picture. I can send a video if it's necessary.

**Comment by thomasdilts** [comment]
This is simply a misunderstanding about how the API works. I guess you could say the API needs to be changed to fix this problem. This is what is happening:
1. When you do a profile-get you will ALWAYS get a picture back. If you have put in a personal picture that is of course the picture you get back. If not you get the automatic picture back of the piano/singer/guitar.
2. BUT, if you then do a profile-change and send the piano/singer/guitar picture back then it is assumed that this picture is now your personal picture and it overrides any default piano/singer/guitar. To quickly fix this you need to delete the photo on the website. Then the default photo will once again start working.

The best way for me to fix this is to do 2 things:
1. The profile-get API will only return the personal photo. In the case there is no personal photo then the photo field will be blank or non-existant.
2. When you do a profile-change and you include the field "photo" but set its value till "null" (without the quotation marks) then you are saying to erase the personal photo.

Please reply if you accept me doing this change in the API

**Comment by eliasalbro95** [comment]
Okay, I got the problem, and about the fixes, yes sure we can do this.
And I'm going to need the same photos you have on the website to use them locally as an alt in case there is no personal photo.

Thank you.

**Comment by thomasdilts** [comment]
The API is fixed as agreed upon and an example is shown in https://github.com/thomasdilts/churchsongs/wiki/User-profile-change .  
![Guitar](https://github.com/thomasdilts/churchsongs/assets/7530620/4e90cc1e-d2ec-4aae-8a45-bbbfe91abff6)
![Piano](https://github.com/thomasdilts/churchsongs/assets/7530620/a3f6b760-f71b-4e4a-ac6b-df78103d458a)
![Singer](https://github.com/thomasdilts/churchsongs/assets/7530620/3d9e670d-0f99-4ea7-8d3f-f8af023e57b8)
![Ukulele](https://github.com/thomasdilts/churchsongs/assets/7530620/fa9b577e-b56d-4b22-b026-4d3ca7a81785)
Attached in this issue are all the singer/guitar/piano/ukelele photos that you may need

**Comment by thomasdilts** [comment]
By the way, your app now crashes because it can't handle the non-existing photo field in the profile-get API
