### ISSUE TITLE
List Change Song API doesn't change the song's chords 

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#105]
[List change song](https://github.com/thomasdilts/churchsongs/wiki/List-changesong) does not change the song's chords when I change the keynote of the song, it only changes the keynote property, not the whole song chords. 
It has to change the whole chords based on the keynote change.

**Comment by eliasalbro95** [comment]
Let me know if I can help with anything, Considering that this issue needs a musical background, I implemented something like this in the app.

**Comment by thomasdilts** [comment]
Fixed. Please test and then close this issue if it works. Please test both English and Arabic songs because it is slightly different code for each

**Comment by eliasalbro95** [comment]
O
