### ISSUE TITLE
Change email option

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#106]
Can make it a requirement to re-verify if anyone change the mail?

**Comment by thomasdilts** [comment]
Thanks for making a new issue. This is quite a bit more difficult than the other problem... It requires new fields and a lot more logic.

**Comment by MalekBakary** [comment]
you don't have to do it right now, Elias has a lot to work with in the app now so take your time :)

**Comment by MalekBakary** [comment]
After rethinking, do we really need to have this option? Why do the users need to change their email?
If it is complicated and will take much time of you so I think we can just ignore it or at least leave it to later. What do you think?

**Comment by thomasdilts** [comment]
Leave it to later perhaps..

**Comment by MalekBakary** [comment]
Can you a least make it unchangeble for now?
