### ISSUE TITLE
"PRIVACY POLICY" and the "TERMS OF SERVICE" 

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#107]
1- Can you please add them to the sign up and put them somewhere under the user picture (or any other place that you think is the best for them)?

2- can you make an API for @eliasalbro95 to use it in the app as well?

**Comment by thomasdilts** [comment]
@eliasalbro95 do you want this perhaps in the version API??

**Comment by MalekBakary** [comment]
I will send them by email cuz it is not working here

**Comment by thomasdilts** [comment]
@eliasalbro95 these privacy and terms are very large.  Uncompressed they are 492713 bytes and 167326 bytes. So a little over half a megabyte together. I think they need their own API because of the size. Would you like me to gzip compress them and then send them as base64 ?

**Comment by eliasalbro95** [comment]
yes, sure that would be great.

**Comment by thomasdilts** [comment]
done. For the backend see https://github.com/thomasdilts/churchsongs/wiki/Policies

for the frontend see https://jesusislord.se/zamar/frontend/web/index.php?r=site%2Ftermsofservice
