### ISSUE TITLE
Add "Back bottom"

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#109]
2- To inside every set page (the page you can see all the songs inside your set)
3- to View all song (when you see all the songs inside the set - there is a bottom called view all songs

**Comment by thomasdilts** [comment]
Time to show some pictures. I have no idea what you are talking about except that it is about sets. Besides that. Nothing. I assume that your use of "Bottom" means "Button". I hope thats right. Anyway I cant do anything until you are more clear

**Comment by MalekBakary** [comment]
Sorry I absolutely mean button. I will send som pictures today 😂

**Comment by thomasdilts** [comment]
done

**Comment by MalekBakary** [comment]
I still miss the back button on the set-song page (the page that show all the songs inside a singel page) like in the picture. And it allows the user to go back to the page with all the different sets
![27](https://github.com/thomasdilts/churchsongs/assets/126695454/3322cac4-3b17-41ab-aad7-57ad189d086c)

**Comment by thomasdilts** [comment]
done
