### ISSUE TITLE
Add a link to copy in the share page

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#110]
To give the user the option to copy the link and share it in his way.

**Comment by thomasdilts** [comment]
Done. Not an option. Removed emailing. Too complicated if we are going to be giving the link as well.

**Comment by MalekBakary** [comment]
Then it will be more smooth if we only give them the link to share there way 🤔 I hardly believe that any one will use this optioned right now and enter the email manually, since the email is the old fashion now (almost only you and me still using it)
We can Change it in the second release if you want to give it a shot
