### ISSUE TITLE
Notifications User Update not working

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#115]
[Notifications user update API](https://github.com/thomasdilts/churchsongs/wiki/Notification-userupdate) is not working and it gives this error code:
`<pre>An Error occurred while handling another error:
yii\base\InvalidRouteException: Unable to resolve the request: site/error in /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php:149
Stack trace:
#0 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller-&gt;runAction()
#1 /var/www/html/zamar/vendor/yiisoft/yii2/web/ErrorHandler.php(109): yii\base\Module-&gt;runAction()
#2 /var/www/html/zamar/vendor/yiisoft/yii2/base/ErrorHandler.php(152): yii\web\ErrorHandler-&gt;renderException()
#3 [internal function]: yii\base\ErrorHandler-&gt;handleException()
#4 {main}`

**Comment by thomasdilts** [comment]
You are getting an InvalidRouteException error. I need to know what route you are using. I think this is your error if you use the routes shown in the wiki you will never get this error.

**Comment by thomasdilts** [comment]
Ok. Now I see from the message that someone is calling the API route site/error. This link definitely does not exist. Who is calling site/error?

**Comment by eliasalbro95** [comment]
I'm trying to get the response of Postman using this route: "https://jesusislord.se/zamar/backend/web/notification/userupdate"
but it gives the previous error.

**Comment by eliasalbro95** [comment]
> Ok. Now I see from the message that someone is calling the API route site/error. This link definitely does not exist. Who is calling site/error?

site/error ?? I don't know, I'm trying to get the "user update API" resposne.

**Comment by thomasdilts** [comment]
When I use Postman and call the link
https://jesusislord.se/zamar/backend/web/notification/updateuser
with the body
{
    "last_notification_date":"2023-08-08 09:26:18"
}
And I give the correct authorization code,
I get the response
{
    "status": 200
}
Perhaps you are sending something strange.
**AHHHHH** . now I see. You have the wrong Address. You have "**userupdate**" but it is **"updateuser"**

**Comment by thomasdilts** [comment]
Sorry. This was my mistake. Error in the documentation. Now the documentation is fixed.
