### ISSUE TITLE
Wrap text

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#116]
In the set-song page if the comment is too long it shows below the list not beside it as it should, and like the songs shows. Can you please add text wrap to it to force it shows in the right place?
![28](https://github.com/thomasdilts/churchsongs/assets/126695454/55b257c9-991b-4c97-94d0-e06f8e2fba20)

**Comment by thomasdilts** [comment]
done. Before testing clear your cache.
