### ISSUE TITLE
When I tried to change a date and time for a set

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#123]
Database Exception – [yii\db\Exception](https://www.yiiframework.com/doc-2.0/yii-db-exception.html)
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '07‏/02‏/2030، 9:00:00 ' for column `zamar`.`user_lists`.`custom_date` at row 1
The SQL being executed was: UPDATE `user_lists` SET `custom_date`='07‏/02‏/2030، 9:00:00 ' WHERE `id`=291
Error Info: Array
(
    [0] => 22007
    [1] => 1292
    [2] => Incorrect datetime value: '07‏/02‏/2030، 9:00:00 ' for column `zamar`.`user_lists`.`custom_date` at row 1
)
↵
Caused by: PDOException
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '07‏/02‏/2030، 9:00:00 ' for column `zamar`.`user_lists`.`custom_date` at row 1
in /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php at line 1302

**Comment by thomasdilts** [comment]
seems to work now for me.
