### ISSUE TITLE
Add a comment block

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#124]
1- Why do we need language there? can we remove it if there is nothing that I missed (not talking about the Bible language)

2- in the comment section it says: Notes to appear on the printout. Which is not true. Can you change it to "add your comment" for example?

3- In English it is the same word that describe the title here and the song title, but in Arabic they are totally different words. But I  can't change it since there is only one title word in the Arabic table. If you want to change it your self so the word for the comment title in Arabic is: العنوان otherwise you can add it to the table and I will change it.

**Comment by thomasdilts** [comment]
I need to know the language so I know how to align it!!  Align left or right. Just like each song must have a language

**Comment by thomasdilts** [comment]
2. Now changed to simply "Comment"
3. Now changed to "Title of the comment". You need to go to the arabic translations to give a translation for that text.
