### ISSUE TITLE
Can you please make this bar disapeare?

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#129]
In the contact page

![31](https://github.com/thomasdilts/churchsongs/assets/126695454/6e808190-7aff-4f46-b96a-9bcbbb54df0c)

**Comment by thomasdilts** [comment]
Bar gone from contacts

**Comment by MalekBakary** [comment]
The same bar is shown in the: 
1- Request password reset
2- Resend verification email

**Comment by thomasdilts** [comment]
Gone
