### ISSUE TITLE
In the set page

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#130]
The share and the delete icons flys away in screens smaller than 468px unfortunately there is good amount of mobiles that have a small screen.

![30](https://github.com/thomasdilts/churchsongs/assets/126695454/3ef7c16c-2077-4a74-a5bb-43dabd7b85b1)

**Comment by thomasdilts** [comment]
Well, I clipped their wings so they won't fly away anymore. However I disagree that there are so many with such small screens.

**Comment by MalekBakary** [comment]
Finally, your work with the chicken, gave you experience with the wings 🐔 
Believe it or not, I have iPhone 13 and the viewport size is 390 pixel !! And that's how I found about the flying wings 🤓

**Comment by MalekBakary** [comment]
Anyway it seems that they are still flying. The picture done is from my phone. 
Please try to open it on browser with your phone. Maybe it is some problem with mine 

![image](https://github.com/thomasdilts/churchsongs/assets/126695454/fb53ba09-fc45-415a-b667-9756e41eb643)

**Comment by thomasdilts** [comment]
wow. ok. I really need a small screen to test this

**Comment by thomasdilts** [comment]
strange that the last one worked ....

**Comment by thomasdilts** [comment]
BUT. You must clear the cache. I bet you didnt do that on your iphone...Please do that.

**Comment by MalekBakary** [comment]
I cleared the cache and tried another iPhone that has never opened Zamar befor but still the same problem... The simulator on both Chrome and Edge is showing everything right!!! I really have no idea. maybe we can wait with it for now
