### ISSUE TITLE
Can you make the language and the sort statik in the library page? 

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#132]
Because there is nothing to search for. I mean make them exactly like the (title, text) dropdown menu.

![32](https://github.com/thomasdilts/churchsongs/assets/126695454/2eabeeb8-05d3-4592-b456-6454e403d0fd)

**Comment by thomasdilts** [comment]
Don't have any idea what you mean. What does "statik" mean to you? To me static means "it is always there". Which it always is. Therefore I have no idea what you are talking about.

**Comment by MalekBakary** [comment]
I knew it will come 😂
If you press in the white box where it says English, you will see that you can search for the language. Since we have only tow languages we don't want it. 
We need to make it unsearchable exactly like the meny beside the search bar (title, text)
