### ISSUE TITLE
Can you change the icons in the language menu?

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#133]
The svg files is sent to you by mail
![33](https://github.com/thomasdilts/churchsongs/assets/126695454/015a00fb-aed8-45c8-867b-99b4feebe061)

**Comment by thomasdilts** [comment]
You've got to be kidding me??? You have "English" and right beside you want an icon that says "En". That is just plain ridiculous. You've got to come up with something better than that. Just get rid of the stupid icon!!!

**Comment by MalekBakary** [comment]
Actually you talk logic now, aging I cant argue with that. Just get rid of the stupid icon

**Comment by thomasdilts** [comment]
icons removed. Clear your cache. It now looks quite different because it's a completely different solution. It's the standard bootstrap solution
