### ISSUE TITLE
Can you make the background transparant for the chords in the library page

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#134]
OBS! transparant is important if possible, to give me the abelite to change the background color in the future.

![34](https://github.com/thomasdilts/churchsongs/assets/126695454/595011db-4870-4198-a19d-921ac21ef4af)

**Comment by MalekBakary** [comment]
I will come back to you with the exact color in this case after I start with the css... whoever is it possible to make it white or transparent only in the print out with black strings?

**Comment by thomasdilts** [comment]
Yes

**Comment by thomasdilts** [comment]
printout is now background white, black strings
