### ISSUE TITLE
show the chords diagram when hover over them

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#136]
Is it something simple (since we have all the chords in our library) or something that has to wait to the seconded release? 

Please check out what I mean by hovering over any chords in the following link:
https://tabs.ultimate-guitar.com/tab/john-lennon/now-and-then-chords-680794

**Comment by thomasdilts** [comment]
By the way, for the click to work you must choose Guitar/ukulele/piano in the chords section

**Comment by thomasdilts** [comment]
done
