### ISSUE TITLE
Songs Versions API give an ERROR

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#137]
[Songs Versions](https://jesusislord.se/zamar/docs/zamardocs.html#song-versions) gives the following error.
`{
    "name": "PHP Warning",
    "message": "Undefined array key \"appVersionChanges\"",
    "code": 2,
    "type": "yii\\base\\ErrorException",
    "file": "/var/www/html/zamar/backend/controllers/SongController.php",
    "line": 259,
    "stack-trace": [
        "#0 /var/www/html/zamar/backend/controllers/SongController.php(259): yii\\base\\ErrorHandler->handleError()",
        "#1 [internal function]: backend\\controllers\\SongController->actionVersions()",
        "#2 /var/www/html/zamar/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()",
        "#3 /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()",
        "#4 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()",
        "#5 /var/www/html/zamar/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction()",
        "#6 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(384): yii\\web\\Application->handleRequest()",
        "#7 /var/www/html/zamar/backend/web/index.php(18): yii\\base\\Application->run()",
        "#8 {main}"
    ]
}`

**Comment by thomasdilts** [comment]
First time I decided not to test a change, it fails. Now it is working..
