### ISSUE TITLE
Buttons don't change directionality depends on website language

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#139]
OBS!! Can you on your way make the (print) on the same line as the (Transpose)?

![37](https://github.com/thomasdilts/churchsongs/assets/126695454/4125b98e-b7c2-4d8c-bce1-3b7db979c03c)

**Comment by thomasdilts** [comment]
This whole page was looking really bad due to button alignments in arabic/english/mobileDevices and even normal web page. I had to completely rewrite it. Now it is looking really good in all situations.. Really Really good.
