### ISSUE TITLE
Transpose need to be separated in minor and major scale.

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#146]
The transpose dropdown needs to detect the scale (whether it's major or minor) and show only the right chords for the scale.
In **major** chords should show these chords:
C
C#(or Db)
D
D#(Eb)
E
F
F#(Gb)
G
G#(Ab)
A
A#(Bb)
B

**minor**
Am
A#m(Bbm)
Bm
Cm
C#m(Dbm)
Dm
D#m(Ebm)
Em
Fm
F#m(Gbm)
Gm
G#m(Abm)

**Comment by thomasdilts** [comment]
Can you please check if it is correct now?

**Comment by eliasalbro95** [comment]
The current implementation is incurrect.
Let me try to explain myself better, if the keynote of the song is one of the following list **(C, C#, D, Eb, E, F, F#, G, G#, A, Bb, B)** then the transpose's options will be will be **this list,** 
or if the keynote of the song is one the following list **(Am, Bbm, Bm, Cm, C#m, Dm, Ebm, Em, Fm, F#m, Gm, G#m)** then the transpose's options will be **this list**.

let me know if that made it clear.

**Comment by thomasdilts** [comment]
Yes I think you were clear. Can you please check it out now?

**Comment by eliasalbro95** [comment]
Yes, it's correct now.
God bless you.
