### ISSUE TITLE
Song index paging system looks terrible..

### ISSUE THREAD

**Issue by thomasdilts** [thomasdilts/churchsongs#19]
![image](https://user-images.githubusercontent.com/7530620/232796546-dc7a8830-8f76-4c14-ba36-00f6480be835.png)

**Comment by thomasdilts** [comment]
fixed with a little CSS.
![image](https://user-images.githubusercontent.com/7530620/232811054-5066d053-9ade-4bf0-818e-b917d17ae35f.png)

**Comment by MalekBakary** [comment]
Very nice thank you
