### ISSUE TITLE
Unfixable bug with has-chords filter searching for song

### ISSUE THREAD

**Issue by thomasdilts** [thomasdilts/churchsongs#20]
if you set the HasChords filter to "yes" then the search is perfectly correct.
If you set the hasChords filter to "no" then the search will find a few false postitives as well as all the ones that actually have no chords. The false positives are because there are several rows without chords.

MALEK: you must decide if we keep this filter or perhaps simply remove the "No" choice since that is the one that doesn't work perfectly well.

**Comment by MalekBakary** [comment]
We can decide when we meet next time. I'm not sure if I get it 100%

**Comment by thomasdilts** [comment]
its ok. I fixed this. I know I said it couldn't be fixed but I meant it couldnt be fixed with the technique I was using. I changed to another technique.
