### ISSUE TITLE
Tags and Authors page

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#21]
1- Can we get "Columns" in Tags and Authors page similar to the one we have on Songs page? To give the abelite to hid and show columns.
2- Dynamic search function os not working on tags and authors page. We need to press enter befor it shows the search.

**Comment by thomasdilts** [comment]
We can eventually take a look at improving these pages but remember these are only for our editors and not for normal members. Therefore they are really not that important to get perfect. Why waste a lot of time on things that are not important.

**Comment by MalekBakary** [comment]
Okay, I thought it was only a bug or something very simple to do. You absolutely don't need to put time on it.
