### ISSUE TITLE
When I tried to enter a song, then the website stopped working for 2-3 min

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#24]
ParseError: syntax error, unexpected '}' in /var/www/html/zamar/common/models/User.php:361
Stack trace:
#0 [internal function]: yii\BaseYii::autoload()
#1 /var/www/html/zamar/vendor/yiisoft/yii2/web/User.php(698): spl_autoload_call()
#2 /var/www/html/zamar/vendor/yiisoft/yii2/web/User.php(199): yii\web\User->renewAuthStatus()
#3 /var/www/html/zamar/vendor/yiisoft/yii2/web/User.php(367): yii\web\User->getIdentity()
#4 /var/www/html/zamar/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#5 /var/www/html/zamar/vendor/yiisoft/yii2-debug/src/panels/UserPanel.php(83): yii\base\Component->__get()
#6 /var/www/html/zamar/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\panels\UserPanel->init()
#7 [internal function]: yii\base\BaseObject->__construct()
#8 /var/www/html/zamar/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#9 /var/www/html/zamar/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#10 /var/www/html/zamar/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#11 /var/www/html/zamar/vendor/yiisoft/yii2-debug/src/Module.php(253): yii\BaseYii::createObject()
#12 /var/www/html/zamar/vendor/yiisoft/yii2-debug/src/Module.php(225): yii\debug\Module->initPanels()
#13 /var/www/html/zamar/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\Module->init()
#14 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct()
#15 [internal function]: yii\base\Module->__construct()
#16 /var/www/html/zamar/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#17 /var/www/html/zamar/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#18 /var/www/html/zamar/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#19 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(445): yii\BaseYii::createObject()
#20 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(313): yii\base\Module->getModule()
#21 /var/www/html/zamar/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#22 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(271): yii\web\Application->bootstrap()
#23 /var/www/html/zamar/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\base\Application->init()
#24 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#25 /var/www/html/zamar/frontend/web/index.php(18): yii\base\Application->__construct()
#26 {main}

**Comment by thomasdilts** [comment]
SORRY! this was when I was doing the Gravitar thing. Now its working ... :)
