### ISSUE TITLE
Song Get API

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#26]
Sort by keynote still with the old sort method (A,B..etc.).

**Comment by thomasdilts** [comment]
There have been MANY changes in the filtering and sorting and I need to bring the WEB and the Backend back together again. Unfortunately that means I need to do some rather big changes in the definition of the filtering especially. So I hope you haven't done too much programming with this GetSong interface. It will take me a day or 2 to fix this.

**Comment by thomasdilts** [comment]
Finished. Please see the wiki documentation. It has changed greatly. But now you have all the searching and filtering power you get in the web-gui. ALSO you can decide to not get the texts in the case when you want only to show an overview of the songs. This is the most important for you I think..

**Comment by eliasalbro95** [comment]
Wow. it changes significantly, that's amazing.
God bless!
