### ISSUE TITLE
Page Change request

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#33]
1- Can we have an easy way to find them? Like the page that we have for the Song Deletes under Editor?

2- Can we see the changes in other color when we open the Comparison View? I mean only the things that is changed in red color?

**Comment by thomasdilts** [comment]
1 - Yes. We could do that but really is it so difficult to just open the filter and put in the changeRequest filter in the status? I was at first thinking of doing like you are requesting but then I realized that this is much simpler and better as it is today.
2 - Yes, I have been planing to do this from the very beginning but I just never got around to doing it. At the same time it is a lot of work to do this . I will eventually get it done.

**Comment by MalekBakary** [comment]
1- oh my bad, didn't know that we can find them that way. I thought we have to find them manually 😅 in this case it is good for.

2- thanks 🙏
