### ISSUE TITLE
Chorus numbers

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#36]
In 99% of songs there is only one chorus. Is it possible to remove the number 1 beside the word chorus? It's kind of annoying.

The same for verse, sometimes we have only one vers in the song. Is it possible to remove the number only when we have one verse?

**Comment by MalekBakary** [comment]
Is this reasonable to ask?

**Comment by MalekBakary** [comment]
As soon as you do it, you don't need to like it 😂

**Comment by thomasdilts** [comment]
No more numbers if only one Verse/Chorus. However, if there are more than one verse/chorus but in the set they define that they only want to see one verse, then the verse number will still show. I think that is good. Doing something else would be too difficult

**Comment by MalekBakary** [comment]
It is good and more than enough thank you
