### ISSUE TITLE
Song Get 500 Internal server error 

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#38]
Sometimes, when I refresh and request the songs again, this API returns a '500 internal server error' despite the fact that the authorization is still valid. 
I initially suspected it to be a bug within the application, but upon further investigation, I couldn't find any issue. Therefore, I would like to confirm that this issue is not caused by the backend and that I should investigate it further. 

Thank you.

**Comment by eliasalbro95** [comment]
This is the error code the API gives:
```
An Error occurred while handling another error:
 yii\base\InvalidRouteException: Unable to resolve the request: site/error in /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php:149
```

**Comment by thomasdilts** [comment]
The only addresses that exist for "site" are the following:

https://jesusislord.se/zamar/backend/web/site/signup
https://jesusislord.se/zamar/backend/web/site/login
https://jesusislord.se/zamar/backend/web/site/resetpassword

Obviously your code for generating these addresses is going a little crazy.

**Comment by eliasalbro95** [comment]
Found it, thank you for the extended information.
