### ISSUE TITLE
Song Get 

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#39]
'orderof' field is not included with 'returnfields' parameter.

**Comment by thomasdilts** [comment]
I don't agree. When I send a song/get with the body
{
    "how-many-per-page": 20,
    "page-number": 10,
    "returnfields":["id", "title", "title2", "bibleverse", **"orderof"**],
    "option-chords": "IncludeInTexts",
    "sort-by": {"field":"id","direction":"ASC"},
    "filters":[{"field":"iso_name", "like":"ar"}]
}
Then I get the following:

{
    "status": 200,
    "total-count": "302",
    "page": 10,
    "data": [
        {
            "id": 420,
            "title": "إلهي حي مش بين الأموات",
            "title2": "",
            "bibleverse": "",
            "orderof": "V1 V2 V3"
        },
        {
            "id": 421,
            "title": "إلهي يسوع",
            "title2": "",
            "bibleverse": "أشعياء 53 : ",
            "orderof": "C1 V1 V2"
        },
        {
            "id": 423,
            "title": "إملا حياتنا من مجدك",
            "title2": "",
            "bibleverse": "",
            "orderof": "V1 V2 V3 V4"
        },
...
}

So I don't understand what the problem is that you have. Can you be more specific?

**Comment by eliasalbro95** [comment]
Weird!
That doesn't work the last time I checked it out.
It seems it was something wrong I did.
