### ISSUE TITLE
Sets/list add a comment block section to the list

### ISSUE THREAD

**Issue by thomasdilts** [thomasdilts/churchsongs#4]
1. add bible verses to the comment block
2. eventually add the entire verse but begin with only the verse number

**Comment by thomasdilts** [comment]
I don't have any idea what this is. Do you?

**Comment by MalekBakary** [comment]
I tested it and it works fin. thank you. 
Only one thing. can you make it go directly to the set view after pressing the save button?
I mean to the page that show all the songs and comments in the chosen set.
Now it shows the comment and it takes some steps to ge back to the set page which is annoying.

**Comment by MalekBakary** [comment]
Thanks.
You remember that we need to have Bible verses in the comment block?

**Comment by thomasdilts** [comment]
I think we should leave that for a much later date. I mean, you don't want just "bible references", you want real whole bible verses in both english and arabic. It's not impossible but  a whole lot of work and people know how to copy and paste their own bible verses from their favorite bible into the comment instead of using some bible version I force on them.
