### ISSUE TITLE
When making a change request. If Admin => to approve page 

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#42]
As it is when admin add a song. It goes direkt to approve page. It will make my life much easier specially now when I have another people entering the songs, an I often need to change something in it.

**Comment by thomasdilts** [comment]
I'm not really sure what you want here because we have talked about this many times. What I have done is that if you are administrator then when you UPDATE or CREATE a song, it always goes directly to PUBLISHED. No approval or submitted stage.

**Comment by MalekBakary** [comment]
It should be Edit not Add sorry 😥 and sorry for not being clear.

I mean when admin add a song after pressing save it goes directly to page for approve which is perfect.

But when Admin edit a song it not do the same. I wanted to go directly to page for approve after save editing. 

I think your way works as well. Thank you
