### ISSUE TITLE
Languge

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#43]
The worde "Text" used in 2 different places:
1- When it mean the person who wrote the song in the authors
2- In the song list when it means the actual song text. 
In Arabic is tow different word and I can't see that you have tow different options in the language editing file.

**Comment by thomasdilts** [comment]
This has been fixed. It is now called "Written by" in English. I have added it to the arabic list. Please ASAP change it to the correct arabic..

**Comment by MalekBakary** [comment]
Fixed, and thank you for doing it.
