### ISSUE TITLE
Every singel "List" need to be changed to "Set" / "Sets"

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#44]
Absolutely the one that has this mening. I'm not sure if you used it in another context like user list or something like that.

**Comment by thomasdilts** [comment]
Are you really really sure? I'm afraid that this change will result in 90% of people not understanding what a Set is. !0% will get it but the rest will be lost. Yes, in a recording studio or in the film industry people will understand this but not the average person. The word "set" has over 10 different meanings. "list" has only one meaning.

**Comment by MalekBakary** [comment]
I'm sure, cuz our target group is musicians that are used to this term. If we use not musical terms we will confuse them.

**Comment by MalekBakary** [comment]
![image](https://github.com/thomasdilts/churchsongs/assets/126695454/9aed315e-d423-4e3a-acd4-7976d0dce4e8)

This is screenshot from the most famous app in this field. They use sets

**Comment by thomasdilts** [comment]
You asked for it. You got it. Even if you are just copying what others do.. :)

**Comment by MalekBakary** [comment]
Thank you. Sometimes we don't need to think out of the box 😉
