### ISSUE TITLE
When saving without adding any verses or chorus, it shows the message in wrong place

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#45]
![12](https://github.com/thomasdilts/churchsongs/assets/126695454/15a1d586-329f-4081-9d9a-100e3ac893f1)

**Comment by MalekBakary** [comment]
And for some reason I can't find this massage in the language page to edit it in Arabic.

**Comment by thomasdilts** [comment]
These texts are stored in another place/system... Thats why you cant find them.

**Comment by MalekBakary** [comment]
okay, then I will write it to you here>
Title cannot be...: يجب إضافة عنوان

Orderof cannot...: يجب إضافة مقطع واحد على الأقل ليتم الحفظ

Maybe we can change the English as well cus it is not so clear, something like:
Add a vers.
