### ISSUE TITLE
Can add empty comment block

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#48]
It will be better to have requirement to add text and maybe title

**Comment by thomasdilts** [comment]
I disagree. Empty comment blocks don't hurt anything and they are easily removed. If I require a title but what if they only want a note? Or I require a note and they only want a title? You see, there is a method to my madness.

**Comment by MalekBakary** [comment]
Nice argument, I agree, but can we require them to add something? I mean either title or note? Other wise it can be many totally empty comments blocks and it is not useful for any thing

**Comment by MalekBakary** [comment]
After many discussion with Elias ans couple of other worship leader, we come to that they need only the Notes. There the can write any thing they want inclusive the title. In other word we don't need the title. and it is more logic to make it mandatory to write something in the note block sins it is the only block that we have.

**Comment by MalekBakary** [comment]
Another thing that I didn't get, why do we have language block? I know it is there for a reason but still cant find it :)

**Comment by thomasdilts** [comment]
The language is for the bible. You really don't know what language they want the bible verse from.

**Comment by thomasdilts** [comment]
Now you get errors if neither title or notes is filled in. One or the other must be filled in.

**Comment by MalekBakary** [comment]
I mean the first one. I know that the second one is for the bible language.There is tow places for the language. 

![image](https://github.com/thomasdilts/churchsongs/assets/126695454/1995135e-347a-4e92-a5ce-77ff2347c02a)

**Comment by MalekBakary** [comment]
Don't you want to remove the title totally?
