### ISSUE TITLE
CSS contact us

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#54]
.contact-talk-to-us{
.contact-have-any-questions{

is connected to each others. I can't change anything in one of them without having the other changed.

**Comment by thomasdilts** [comment]
I have no problem to change them separately. But then again, as usual I probably have no idea what you want. I can't read your mind. 
.contact-talk-to-us{
    color:green;
}
.contact-have-any-questions{
     color:red;
}
This makes one with a red color and one with a green color. Completely separate.

**Comment by MalekBakary** [comment]
For some reason if I changed one of them it changes the other one automatically!! But not today it worked fin for mig, it might be something I did wrong
