### ISSUE TITLE
Upload photo

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#55]
1- Can we make it circle "Drag & drop files here …" Cuz we show only circle photo so no idea to have it rectangle. 
2- Can we give the user the ability to crop the photo to make it fit? Se the result in my account Malek Test

**Comment by thomasdilts** [comment]
ok. so you want to change your sex now? A woman... hmmm. ok. I guess its an ok look if that is what you want .

**Comment by thomasdilts** [comment]
You're asking a lot. But I will think about it. Yes, the interface I made here is VERY confusing and irritating. Needs to be better.

**Comment by MalekBakary** [comment]
Check out this demo. I like the one with the cirkel icon, in the bottom of the page. They offer the code as well but the question is dose it work for us? or are we using something different? 

https://pqina.nl/filepond/#profile-picture-demo
