### ISSUE TITLE
Navigation bar has different color than the website and I couldn't change it

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#57]

**Comment by thomasdilts** [comment]
You had a hard time with this because it was controlled by something called scss (allows light and dark modes) which even I don't know how it works. But I managed to go around this scss and now it is controlled by this line in site.css
  .zamar-nav {
    background-color: var(--zamar-less-dark-background);
  }

**Comment by MalekBakary** [comment]
Thank you

**Comment by thomasdilts** [comment]
done. You just needed to add !Important after the zamar-nav in the site.css..
  .zamar-nav {
    background-color: var(--zamar-dark-body-background) !important;
  }
