### ISSUE TITLE
Can you please remove the slide from the "We are with you "

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#58]

**Comment by thomasdilts** [comment]
As usual, I have absoutely no idea what you are talking about. Please when you write these think a little about my situation. I can't read your mind. Perhaps a picture if you can't be more specific in any other way

**Comment by MalekBakary** [comment]
This one ![image](https://github.com/thomasdilts/churchsongs/assets/126695454/6f3cc653-1ed9-42c3-82ca-f7070e08f0f7)

**Comment by thomasdilts** [comment]
got it. fixed
