### ISSUE TITLE
"We are with you on" need som changes

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#60]
I couldn't remove the margin in purple, maybe it will be easier for you to do it with the grid

![14](https://github.com/thomasdilts/churchsongs/assets/126695454/4f820998-51e8-474b-9265-736bd9150a4f)

**Comment by thomasdilts** [comment]
add some margin

**Comment by MalekBakary** [comment]
I fixed the margin, I need help with the mobile version. I can't get it right. Any suggestions?

 
![17](https://github.com/thomasdilts/churchsongs/assets/126695454/b5f08822-735f-4af3-b9b0-a702e7d93fc2)

**Comment by thomasdilts** [comment]
fixed. If you mess it up again, fix it yourself.
