### ISSUE TITLE
Testimonial slider changes! 

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#61]
1- the slider start on the left side sometimes. 
2- Can you PLEASE change the quotation icon? I already sent it to you by email.
3- Please make the text box bigger so we can remove  the "more"
4- "@working place" has to be in a new line under the work line.
4- If you cant figure out the problem with the blurry slide sometime soon I will find another way to do the slide. (But as usually you find a solution for every thing so I will wait) 

![15](https://github.com/thomasdilts/churchsongs/assets/126695454/3dc7d6a8-dc6f-4999-b2dc-48d960a053ec)

**Comment by thomasdilts** [comment]
find the new slider for this one

**Comment by MalekBakary** [comment]
I found one that will work hopefully. It is still supported from the developer and updated 
https://uiinitiative.com/catalog/carousel-slider

it is from https://swiperjs.com/demos

maybe it is the same swiper that you use but a newer model

**Comment by thomasdilts** [comment]
You must choose one of the items in the Demo at https://swiperjs.com/demos .
The carousel-slider is something you must pay for and I refuse to pay. Plus the licensing is probably a nightmare. Choose and let me know.

**Comment by thomasdilts** [comment]
Forget it. Give me a chance. I think it might be free. They are just trying to get some money.

**Comment by thomasdilts** [comment]
Darn. It doesnt work in chrome. Only firefox... oh well.

**Comment by thomasdilts** [comment]
now it's working in chrome as well but you will probably say it's blurry. This is using your favorite carousel slider. I'm finished with this. I've wasted 5 hours on this. No more

**Comment by MalekBakary** [comment]
Thank you, it is better now. Still has the problem of not centering but I can live with it for now. 
Please Change the icon that you are ignoring so we can close this issue 😉

**Comment by thomasdilts** [comment]
Icon changed now. You must clear the cache to see it. Sorry about my last comment. I was really frustrated after hours of playing with the swiper. At one point it was absolutely perfect using an extremely old version of the swiper. But in chrome it looked terrible. Now we are using the latest swiper version and well, it is what it is...

**Comment by MalekBakary** [comment]
Thank you. I just didn't liked that you spent so much time on it.  Please in the future. Tell me if something is too complicated so we can change it, I don't want to spend your time on small things. I know how it feels because I have the same problem with the CSS. Thank you for all your work. You are amazing.🙏
