### ISSUE TITLE
List Delete is not working now.

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#64]
this is the error i get:
`{
    "name": "Integrity constraint violation",
    "message": "SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`zamar`.`share_list_token`, CONSTRAINT `idkwor_listsongsshareaccesst` FOREIGN KEY (`user_lists_id`) REFERENCES `user_lists` (`id`))\nThe SQL being executed was: DELETE FROM `user_lists` WHERE `id`=181",
    "code": "23000",
    "type": "yii\\db\\IntegrityException",
    "file": "/var/www/html/zamar/vendor/yiisoft/yii2/db/Schema.php",
    "line": 676,
    "stack-trace": [
        "#0 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1307): yii\\db\\Schema->convertException()",
        "#1 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1102): yii\\db\\Command->internalExecute()",
        "#2 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(405): yii\\db\\Command->execute()",
        "#3 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(765): yii\\db\\ActiveRecord::deleteAll()",
        "#4 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\\db\\ActiveRecord->deleteInternal()",
        "#5 /var/www/html/zamar/backend/controllers/ListController.php(248): yii\\db\\ActiveRecord->delete()",
        "#6 [internal function]: backend\\controllers\\ListController->actionDelete()",
        "#7 /var/www/html/zamar/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()",
        "#8 /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()",
        "#9 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()",
        "#10 /var/www/html/zamar/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction()",
        "#11 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(384): yii\\web\\Application->handleRequest()",
        "#12 /var/www/html/zamar/backend/web/index.php(18): yii\\base\\Application->run()",
        "#13 {main}"
    ],
    "error-info": [
        "23000",
        1451,
        "Cannot delete or update a parent row: a foreign key constraint fails (`zamar`.`share_list_token`, CONSTRAINT `idkwor_listsongsshareaccesst` FOREIGN KEY (`user_lists_id`) REFERENCES `user_lists` (`id`))"
    ],
    "previous": {
        "name": "Exception",
        "message": "SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`zamar`.`share_list_token`, CONSTRAINT `idkwor_listsongsshareaccesst` FOREIGN KEY (`user_lists_id`) REFERENCES `user_lists` (`id`))",
        "code": "23000",
        "type": "PDOException",
        "file": "/var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php",
        "line": 1302,
        "stack-trace": [
            "#0 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()",
            "#1 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1102): yii\\db\\Command->internalExecute()",
            "#2 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(405): yii\\db\\Command->execute()",
            "#3 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(765): yii\\db\\ActiveRecord::deleteAll()",
            "#4 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(724): yii\\db\\ActiveRecord->deleteInternal()",
            "#5 /var/www/html/zamar/backend/controllers/ListController.php(248): yii\\db\\ActiveRecord->delete()",
            "#6 [internal function]: backend\\controllers\\ListController->actionDelete()",
            "#7 /var/www/html/zamar/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()",
            "#8 /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()",
            "#9 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()",
            "#10 /var/www/html/zamar/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction()",
            "#11 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(384): yii\\web\\Application->handleRequest()",
            "#12 /var/www/html/zamar/backend/web/index.php(18): yii\\base\\Application->run()",
            "#13 {main}"
        ]
    }
}`

**Comment by thomasdilts** [comment]
Fixed. Works now
