### ISSUE TITLE
List Get one set only

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#67]
Could we add a Get API for an individual set? 
Within the Set's screen, I am implementing multiple processes such as adding, deleting, and reordering. It would be inefficient to call the API for the entire set list and manually search for the selected set in order to retrieve the desired changes.

**Comment by thomasdilts** [comment]
Yes. I will do it later today.

**Comment by thomasdilts** [comment]
Interesting. You know, I already have done this. I anticipated that you would want this. But I think the name of it is why you couldn't find it. It is this call   https://github.com/thomasdilts/churchsongs/wiki/List-getonesong   .  Yes the name is a little strange but I think this is exactly what you want.

**Comment by thomasdilts** [comment]
Now that I read your comment maybe the last comment wasn't the one you wanted. BUT it is still already done if it is just one list that you want. You need to call list-get with the filter id=12345 and then you get just one list.

**Comment by eliasalbro95** [comment]
Oh, right! I forgot that there is a filter in this API too.
That's exactly what I need.
Thank you, I'm closing this issue.
