### ISSUE TITLE
Fix the signup/signin page. Prioritize

### ISSUE THREAD

**Issue by thomasdilts** [thomasdilts/churchsongs#70]

**Comment by thomasdilts** [comment]
This is the first draft finished of the signin and signup pages. Don't freak out that it isn't exactly as you designed. You need to understand that we are using the "bootstrap" templates which decide how a lot of things look and feel. I changed the captcha a little bit. You probably still hate it but it is better because it doesn't require "abcd..." but instead "123..."

**Comment by MalekBakary** [comment]
I was ready for the worst, but it is good! Only some CSS and it will look beautiful. Thank you!

Some small things to fix in it befor we close this issue:

1- Can you please add the " I have read and agree to the terms of service " and make the words "terms of service" in a separated from the rest of the sentence. I will make them green and add hyperlink to the term page which we will create in the feature.  

2- Can you move the password up? it has to be under the email.

3- In Firma I made 2 fields for the password, the seconded one is for confirm. Do we need it or I'm a old school?

4- I started to accept that you don't want the Google captcha. But I think the one you had in the beginning was better and easier to understand. I think this one will be more complicated for people to understand and answer. I know it is a simple math but I think specially the minus will confuse the people cuz they will think it is a dash! 
Can you please change it back to the "abcd..." And can I change the look in CSS?

**Comment by thomasdilts** [comment]
3-- yes old school. When you have the possibility to see the password you don't need to write it twice. There is a ✅ beside you can hit to see the password

**Comment by MalekBakary** [comment]
3- can you change the ✅ and make it 
<i class="fa-sharp fa-light fa-eye"></i>
and 
<i class="fa-light fa-eye-slash"></i>

**Comment by thomasdilts** [comment]
Well, it's not impossible. Its just that this is a finished component.  I will look into it. You're probably right that it will look better with the eye instead.

**Comment by thomasdilts** [comment]
What do you think of this password input widget? Better?
https://www.yiiframework.com/extension/eluhr/yii2-password-input

**Comment by MalekBakary** [comment]
Much better 👍

**Comment by MalekBakary** [comment]
But the roll that they have in the example is weird, why anyone would like to have " must contain the letter a" ?

**Comment by thomasdilts** [comment]
Is this ok?  https://jesusislord.se/zamar/frontend/web/index.php?r=site%2Fsignup
I know you want the EYE to be after the password box but that is impossible. Either accept this one or we go to the 
https://www.yiiframework.com/extension/eluhr/yii2-password-input

**Comment by thomasdilts** [comment]
or I could put it after the security guage but not between the password and the security guage

**Comment by MalekBakary** [comment]
I can't se the first example
Forbidden (#403)

**Comment by thomasdilts** [comment]
of course not. You must log out first from zamar.... Then go to the signup

**Comment by MalekBakary** [comment]
Make sense 😅 I think the other one is much better
https://www.yiiframework.com/extension/eluhr/yii2-password-input
Just remove that "must contain the letter a" please, it is so weird

**Comment by MalekBakary** [comment]
Can you please change the word " Language" to Website Language" It will be easier to understand, or what do you think?

**Comment by thomasdilts** [comment]
I know that you think "language" is unclear. And you are right since we have 2 languages. BUT "Website language" doesn't make it any clearer. In fact, it makes it less clear in my opinion. I recommend leaving it as it is until you get a better idea.

**Comment by thomasdilts** [comment]
Sorry but I made my own password input. I think it is the best option. Looks the best. The only requirement is that there are 8 characters. This is sufficient because there is really nothing dangerous a hacker can do that breaks in UNLESS he breaks in as editor or admin. I think this is finished and you can close this issue

**Comment by MalekBakary** [comment]
Thank you
