### ISSUE TITLE
Make a list of search rules

### ISSUE THREAD

**Issue by thomasdilts** [thomasdilts/churchsongs#74]

**Comment by MalekBakary** [comment]
Here is the rolls that we need to add to the one we already have:
1- ه = ة if they are in the end of a word 

2- ي = ى if they are in the end of a word 

3- if و come as a separate letter-> add it to the next word. It is the same as "a" in English so if it is "a table" it has to be "atable".

4- remove all the following wherever they are.
َ ، ّ ، ً ، ُ ، ِ ، ٍ ، ْ ، ٌ ، ـ ، ٰ ، ٓ

If you want to know what they are so here is explaining from the web:

When learning Arabic pronunciation, English speakers may need to understand the diacritical marks used to indicate the sound of words. In Arabic, diacritics are used to clarify the pronunciation and show the placement of non-vocalized letters in a word. For example, the fatha (ـَ) is used to indicate the letter "alif," the damma (ـُ) is used to indicate the letter "waw," and the kasra (ـِ) is used to indicate the letter "ya." The sukun (ـْ) is also used to indicate the absence of a vowel sound in a word. These diacritics help learners improve their pronunciation and understand the correct pronunciation of words.

**Comment by thomasdilts** [comment]
Should be fixed now. Can you please test this and let me know

**Comment by MalekBakary** [comment]
Nr 6 is not working
Nr 2 is not working

Nr 4 can you add " ـ " to the list? it is the only one who is missing

Otherwise it is working
Thank you

**Comment by thomasdilts** [comment]
6 and 2 I didn't even see.  But ok. Now I see them. I'll fix it shortly. Adding that other to 4-- hmmm . What is it? The function I used should remove ALL diacritical marks, even if you forgot to write some down. Is that a diacritical mark?

**Comment by thomasdilts** [comment]
6 and 2 are now added. If you want the addition to number 4 you need to answer my question above. Is that a diacritical mark?

**Comment by MalekBakary** [comment]
Nr 4  the one I want to add is something used in arabic to make the words longer to match other lines. it is simply nothing but distance. see the example:
يسوع = يســــــــــــوع

**Comment by thomasdilts** [comment]
This is now finished. Can you test and close this item

**Comment by MalekBakary** [comment]
Nr 2 is not working
nr 4 and 6 is working

**Comment by thomasdilts** [comment]
Please test again. Nr 2 should be working now.

**Comment by MalekBakary** [comment]
Still not

**Comment by thomasdilts** [comment]
This crazy arabic. Everything is backwards. Try again. This time might work. I can't test it myself

**Comment by MalekBakary** [comment]
Not yet

**Comment by MalekBakary** [comment]
It is exactly like nr 1, can't you just copy it and only change the letters?

**Comment by thomasdilts** [comment]
I know. That is exactly what I did. Still doesn't work...

**Comment by thomasdilts** [comment]
Can you check to make sure that 1 is still working correctly

**Comment by MalekBakary** [comment]
Still working but if you try harder maybe you can ruin it 🤪

**Comment by thomasdilts** [comment]
Ok. I have managed to test it myself and it works. When I test this on the VERY first record with id=147. 
search for 
 في الوادي

Then search for 
 فى الوادي

And you will both times get the same 2 records which means that it works. 
The function I was using worked for 1 but not for 2. So I used a different function for 2 and now it works.

**Comment by MalekBakary** [comment]
you nailed it, nice work and most importantly without ruin nr 1 😂 Thank you

**Comment by MalekBakary** [comment]
Is it possible to add those as well?
ياللي = يلي = يللي = يالي
يارب = يا رب
يايسوع = يا يسوع
يهوى = يهوا = يهوه = يهوة
