### ISSUE TITLE
Positionening

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#78]
1- I fixed all the positioning the way I want them, then I realized that when we have title 2 every thing changes.
2- I fixed the positioning with the title 2 as in the picture (I want the ass to set to be out sid for now so ignore it, I will explained later) But the positions is changing wither there is title 2 or not!
I chose position relativ, which suppose to give the elements position relative to its parents.  As I understand it, if I give something top: 30px it should position it 30px from the top wither if there is other elements or not! dose wat I'm saying make sens? 

If you see in the pic and the blue lines it is not like that!!
Please let me know if you didn't got what I mean. 

![16](https://github.com/thomasdilts/churchsongs/assets/126695454/9b60a5cb-b123-4a15-91d2-a792d75c6788)

**Comment by thomasdilts** [comment]
This is easy to fix. You just need to give it a constant height and all is fixed. Relative positions are the worst way to fix these things. Constant heights are the way to make it work. Then, even if there is no title2, the height will be there.
.song-title2{
  max-height:1rem;
  min-height:1rem;
  text-align: center;
  position: relative;
  top: 25px;
}
