### ISSUE TITLE
Icons!!

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#81]
1- I need help with centering the icon with the text. I tried multiple things but I still get this massage:
The display: block property prevents align-items from having an effect.
Try setting display to something other than block.

I don't know how to change it. and I don't even know what is it! 

2- The text in artist name is slightly down a bit compared to the rest of the authors. Please help me with that

![image](https://github.com/thomasdilts/churchsongs/assets/126695454/65e7677e-f65e-4444-b3de-d89ceba164ad)

**Comment by thomasdilts** [comment]
1. centered
2. all icons level
Dont forget to clear the cache
