### ISSUE TITLE
Add song/comment to specific List (for discussion).

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#83]
Currently, we have a List change that allows adding items to a specific list. However, I am required to handle the existing set's list, add the new item to it, and then post the updated list to the API.

I was wondering if it would be possible to create a dedicated API for adding an item to a list without needing to consider the entire existing list in the process.

**Comment by thomasdilts** [comment]
Absolutely. I'll do this by Monday. I've been really busy taking care of grandchildren this week but now I can get back to work.

**Comment by thomasdilts** [comment]
It's finished now. See https://github.com/thomasdilts/churchsongs/wiki/List-addsongs
