### ISSUE TITLE
Delete one song/comment of a list

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#84]
Can we add another API for Delete only on songs/comments? For the same reasons as the previous issue.

I apologize for not including it in the last issue report; it came to my attention separately.

Thank you, and God bless!

**Comment by thomasdilts** [comment]
Yes absolutely. I am happy to make the changes because I am well aware that the API for the list/set is very basic and needs more. I was just unsure what functions would help you the most. I will get it done today.

**Comment by thomasdilts** [comment]
Finished. See https://github.com/thomasdilts/churchsongs/wiki/List-deletesong
