### ISSUE TITLE
Bible API

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#85]
Since there is no API that has multi translations of the Arabic bible.
The site I'm sending at the end has many bible versions in multi languages but it's a SQLite file for each version, I wonder if we can make an API that can be useful for us and everyone to retrieve the data from it without including it in the application's files (which will increase the application's size which it's something we are avoiding) or we can just add an API to download it from the website at the launch of the application. 

Tell me what we can do to decide which translations we will use.

"https://www.ph4.org/b4_index.php#google_vignette"

**Comment by thomasdilts** [comment]
There are api:s for arabic bibles. https://www.biblegateway.com/ has no direct api but still you can get the verses you want from there with some tricks and some restrictions. They have 2 bibles..
1. Arabic Bible: Easy-to-Read Version (ERV-AR)
2. Ketab El Hayat (NAV)

Then there is a real api at https://scripture.api.bible/ but they only have "Biblica® Open New Arabic Version 2012" ONAV.

I had for many years an app for bible translations and I used the https://crosswire.org system and they have 2 free arabic bible versions to download,

1. AraNAV | New Arabic Version (Ketab El Hayat)
2. AraSVD | Smith and van Dyck's al-Kitab al-Muqaddas (Arabic Bible)

They also have a web api for reading bibles but you must have your own server to install on.. https://crosswire.org/swordweb/

What I am trying to say is that I know this subject rather well. Yes, of course we could do it. But why. Whatever we do they will never like the bible versions that we can offer. So let them get their own bible verses..

**Comment by thomasdilts** [comment]
If you need a bible API now for your app then I recommend you use https://scripture.api.bible/ . It's free and very completely documented. As you perhaps know, I myself am using this api if you go to the sets, choose a set and then add a comment you will see the possibility to select an arabic bible and any verse from the bible and copy it to the comment

**Comment by eliasalbro95** [comment]
Hi Thomas,
sorry for the delay.
You are right, in that case, we don't have to do something that already exists.
Thank you I'm gonna try the APIs that you suggested.
