### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#87]
Amazing work! you get it working!! 
I have one point that will make it even batter (I hope).
The bottoms (clear all, apply filter) has there effect on every thing right now. It will be much better to make there effects only for: keys, artist and tags. What I'm, trying to say is when I search for songs I don't want to press Apply, It has to work if I press Enter. The same for the songs language and the sorting. They are not filters, and has to have immediately effect when I chose them.

**Comment by thomasdilts** [comment]
I agree

**Comment by MalekBakary** [comment]
One more thing, when pressing Clear Filter, can you make it apply at the same time? Right now I need to press clear filter then press apply. It is one click for much :)

**Comment by thomasdilts** [comment]
1. Enter hit in title search field causes apply-filter.
2. Added search button after search field because 'enter' is not always understood by all. But the button is.
3. Change language causes apply-filter
4. change sorting causes apply-filter
5. clear all causes apply-filter
