### ISSUE TITLE
Change Medley API changes only the general item.

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#88]
The current implementation of the change medley API only modifies the Medley added to the library list and does not provide a way to update the same Medley item in the user's set.

This poses an issue because users can only view their created Medleys in their sets. Therefore, when editing a Medley, they need to access it from their set and see the changes reflected there because they cannot see the Medley they created in the library list.

Unlike the list change song API, where existing songs are modified based on their IDs, a Medley situation may involve a completely new combination of paragraphs from various songs. Therefore, it's essential to consider this aspect.

If there is anything I may have overlooked, I am open to hearing your insights.

**Comment by thomasdilts** [comment]
Or you can even use :
https://github.com/thomasdilts/churchsongs/wiki/List-change

**Comment by eliasalbro95** [comment]
okay but in case I used list-changesong, how will you know the verses/choruses I added to the Medley? 
what I'm trying to say is list-changesong is depending on the existing orderof verses that I'm passing and it adds or removes from the existing ones that it has already, but what if I'm adding a whole new verse to it? how it will be provided to the list of verse/chorus that it already has?

if how I write it is not understandable let me know so I could make it more visual.

**Comment by thomasdilts** [comment]
The api I mentioned is only for list information and you already understand that. To change the actual medley verses you must use song/changemedley. I know what verses change/added because you must send the entire medley. I think if you just start using it you will understand

**Comment by eliasalbro95** [comment]
I understand that, and actually, I already implement it, the edit medley functionality that I implemented is depending on song/changemedley API.
but let say what is the problem I'm facing, when I submit the edits I did to the medley, the medley is not changing in the set that I created it inside, it changes only the title, but the keynote, and verses I added are not in the body of the medley info when I fetch the set's data.
I uploaded a video to make the issue more understandable.
https://mega.nz/file/llRT2IhR#tObvQilVrqYRVBqqXcSBrU7j1OOT6oq21zOAeSU66tg

**Comment by thomasdilts** [comment]
That problem I understand. You can in my web interface change the key and add the new verse by simply using the verse order GUI in the 'set' edit screens. In my opinion I think it's dangerous to automatically make the verse order and keynote change in the song set because you have no idea what the user wants in this case. You are guessing the user of course wants the kenote change and verse change. What if he has the medley in several sets???? Do you change all of them?? Maybe some of them he wants the old way??

**Comment by eliasalbro95** [comment]
I understand what you are saying.

I was discussing this with Malek, and we came up with the following:
1- when the Medley is created it will be added to the library list and the user's set.
2- when the user deletes or edits the Medley in his set, it will only affect his version of the medley, not the library list medley too. To sum it up, the delete and edit will be locally for the user's set only, it will not affect the library list's medleys.

I don't know if that is doable if the current Medley process of creating, editing, and deleting functions.
let me know what you think.

**Comment by thomasdilts** [comment]
From what I understand of what you described, What I have done does exactly what you have described. If I could also summarize how it now works.

1. When the Medley is created it will be added to the library list and the user's set.
2. When the medley is changed it will only be changed in the library, NOT the user's set or anyone else's set. The verse-order and key in the set will need to be changed separately for each set if necessary. 
3. When a user deletes his own medley from the library it is deleted from EVERYWHERE.
4. When a user deletes his own medley from his set it is only deleted from that specific set but remains in the library.

I hope this clarifies it and is the same as you have described.
