### ISSUE TITLE
Can you make the code accept a chord with ∅ in it? the chord will look like this [C#∅] or [C#∅]

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#90]
PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xE2\x88\x85' for column `zamar`.`chord`.`chord` at row 1 in /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /var/www/html/zamar/vendor/yiisoft/yii2/db/Schema.php(431): yii\db\Command->execute()
#3 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\Schema->insert()
#4 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()
#5 /var/www/html/zamar/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#6 /var/www/html/zamar/frontend/controllers/SongController.php(393): yii\db\BaseActiveRecord->save()
#7 /var/www/html/zamar/frontend/controllers/SongController.php(450): frontend\controllers\SongController::addSongFromView()
#8 [internal function]: frontend\controllers\SongController->actionCreate()
#9 /var/www/html/zamar/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /var/www/html/zamar/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#13 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#14 /var/www/html/zamar/frontend/web/index.php(18): yii\base\Application->run()
#15 {main}

Next yii\db\Exception: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xE2\x88\x85' for column `zamar`.`chord`.`chord` at row 1
The SQL being executed was: INSERT INTO `chord` (`row_id`, `chord`, `position`) VALUES (22938, 'C#∅', 21) in /var/www/html/zamar/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /var/www/html/zamar/vendor/yiisoft/yii2/db/Schema.php(431): yii\db\Command->execute()
#3 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\Schema->insert()
#4 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal()
#5 /var/www/html/zamar/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#6 /var/www/html/zamar/frontend/controllers/SongController.php(393): yii\db\BaseActiveRecord->save()
#7 /var/www/html/zamar/frontend/controllers/SongController.php(450): frontend\controllers\SongController::addSongFromView()
#8 [internal function]: frontend\controllers\SongController->actionCreate()
#9 /var/www/html/zamar/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#10 /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#11 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#12 /var/www/html/zamar/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#13 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#14 /var/www/html/zamar/frontend/web/index.php(18): yii\base\Application->run()
#15 {main}
Additional Information:
Array
(
    [0] => 22007
    [1] => 1366
    [2] => Incorrect string value: '\xE2\x88\x85' for column `zamar`.`chord`.`chord` at row 1
)

**Comment by thomasdilts** [comment]
Fixed. Now you can add absoutely any characters in the chords. Even arabic 😲
