### ISSUE TITLE
Get Profile API Informations

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#91]
We have the following for each profile:
1- first and last name,
2- email
3- the main language
4- song language
5- user's role(guitarist, pianist..etc)
6- user's photo

**based on the wiki** this is the current received data from the profile get API:
  ```
 {
            "id": 37,
            "role": "Editor",
            "status": 10,
            "created_at": "2023-03-13 23:14:17",
            "updated_at": "2023-03-16 17:00:35",
            "username": "thomas",
            "email": "thomas@jesusislord.se",
            "language": "ar"
        }
```
I have 2 things:
1- I need the rest of the information.
2- how do you want me to upload the photo? base64? or normal upload..etc? let me know how to work it out.

**Comment by thomasdilts** [comment]
The changes are made as you requested. You can find answers to your questions in the following wiki pages.
Note that I have added a new field called last_notification_id that will be later explained when I get the notification system working.

https://github.com/thomasdilts/churchsongs/wiki/User-profile-change
https://github.com/thomasdilts/churchsongs/wiki/User-profile-get
https://github.com/thomasdilts/churchsongs/wiki/User-profile-delete

**Comment by thomasdilts** [comment]
One more small note about the photo. It must be base64 and JPG format and the base64 must start with 
data:image/jpg;base64,
