### ISSUE TITLE
Delete account by the user himself 

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#93]
The registration process needs to have an opposite action, which it's the delete account in the current situation. 
This kind of thing Google and Apple will cause a problem with data protection privacy issues when we submit the application on the stores.

**Comment by thomasdilts** [comment]
This is already done in the web gui. 

![image](https://github.com/thomasdilts/churchsongs/assets/7530620/25ef212d-6ad8-459e-8403-c9d80439cd44)

I recommend that you simply send a person to the web gui to perform this action. Let me know if you think this needs to also be done in the backend.

**Comment by thomasdilts** [comment]
oops. Now I see that you have the API to do this from the backend. ... 
See https://github.com/thomasdilts/churchsongs/wiki/User-profile-delete
