### ISSUE TITLE
Push notifications feature 

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#94]
Malek was asking me to make this feature available for the application, so I need to know how you are going to do that so I would know to implement it in the application.

**Comment by thomasdilts** [comment]
This is not simple. It will take a few days to fix and is rather complex. It requires lots of frontend and backend . PLEASE NO MORE FUNCTIONALITY!!!!!! Otherwise we will never be finished.

**Comment by eliasalbro95** [comment]
agreed. 👀 @MalekBakary

**Comment by thomasdilts** [comment]
The backend and frontend are finished now. See the following to see how to use the backend

https://github.com/thomasdilts/churchsongs/wiki/Notification-get
https://github.com/thomasdilts/churchsongs/wiki/Notification-userupdate
