### ISSUE TITLE
Application's version check API

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#95]
We need to add this one to let the user know that he needs to update the application.
As far as I know, application's version should be in the admin dashboard, and the admin should be able to add a new version so the application should call an API at the very beginning of running the app to check if there is a new one or not? 
But I'm all ears to hear any suggestions if you have.

**Comment by thomasdilts** [comment]
Yes. Very good idea. I will get it done today.

**Comment by thomasdilts** [comment]
This is done. See https://github.com/thomasdilts/churchsongs/wiki/Song-versions

**Comment by eliasalbro95** [comment]
Can we add the total number of songs that we have in the library?
It will help me get the whole library in one API request for the local search, And this will save both time and the number of requests while launching the app

**Comment by thomasdilts** [comment]
done. New field added = 'songs'.  See https://github.com/thomasdilts/churchsongs/wiki/Song-versions

**Comment by thomasdilts** [comment]
This count of songs might not be what you really want. Its not so easy to count songs as you might think. 

Please note that the "songs" field is the number of songs in the status "PUBLISHED". There will probably be many more songs in other status like "MEDLEY" or "REJECTED" or "SUBMITTED" which are not included in this count.

Please let me know if you want to really include ALL songs in all Statuses

**Comment by eliasalbro95** [comment]
That's exactly what I need, that's perfect! 
Thank you, and God bless.

**Comment by eliasalbro95** [comment]
Can we add a message(or updates) parameter to this API?
To show the updates message for the new features or bug fixes along with the notifier of a new version message inside the app.

**Comment by thomasdilts** [comment]
Added parameter appVersionChanges to the version API. See https://jesusislord.se/zamar/docs/zamardocs.html#song-versions
