### ISSUE TITLE
Can we have a page language change bottom?

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#96]
If anyone located in Sweden visits the website, they will automatically see it in Swedish, even before logging in. For instance, if this individual cannot read Swedish, it would be challenging for them to navigate the website without logging in or signing up in Swedish.

Another scenario applies to individuals using proxies, which is quite common in the Middle East due to restrictions. In such cases, the website will display a foreign language.

To enhance user experience, I propose the addition of a simple icon that allows users to change the language if they wish.

OBS! Only Arabic, English and for now Swedish

Please see the picture below:
![22](https://github.com/thomasdilts/churchsongs/assets/126695454/637895eb-7374-4e18-a63a-26cbf0971eee)

**Comment by thomasdilts** [comment]
Wow. And you think I am "old school." This is not how you choose languages these days. You have totally misunderstood how the language is chosen. It has nothing to do with your location. It has to do with what your browser thinks your languages are. Of course the algorithm is slightly different for each browser. It's not based on just one language either. It is a list of languages that you have unconsciously chosen at the time of installation of your browser. If we are talking about chrome then the languages are usually chosen by you many years ago when you first set up your first google account. And chrome can add to that list of languages in certain cases depending on choices you make.

Please give up this idea. This was something interesting 20 years ago. No professional does this anymore.

**Comment by MalekBakary** [comment]
It seems like I am the old school 😅 okay I will close this issue. Thanks for the explanation 🙏
