### ISSUE TITLE
Singup API auth key

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#97]
[Signup API](https://github.com/thomasdilts/churchsongs/wiki/Signup)
After the signup info is submitted, I got  the following response:
```
{
    "status": 201,
    "message": "Check your email to verify your account",
    "data": {
        "email": "eliasalbro97@gmail.com",
        "firstname": "test",
        "lastname": "test",
        "songrole": "Leader",
        "songlanguage": 3,
        "language_id": 3,
        "password_hash": "$2y$13$D4zuJ7wIVZzk9gW0JlZZIeax4tixdRjvF2yLPKHoeJ1n2pJF3JxxO",
        "auth_key": "ARiGhFofyGoevk-UtCIakiQYWkO6pp8X",
        "verification_token": "O1zyFB3IypS7tgPW1E85kAahugzmu4Hn_1691515032",
        "songcolumns": 2054,
        "status": 9,
        "id": 107
    }
}
```
and after this, I continue to the verification step and everything is working fine.
### now the question is:
**After** I verified the account when I use the "auth_key": "ARiGhFofyGoevk-UtCIakiQYWkO6pp8X" as a token for authorization for [List Get API](https://github.com/thomasdilts/churchsongs/wiki/List-get) (and I think the other APIs that need authorization will cause the same problem too)
it gives me a response that I'm not authorized 
`{"name":"Unauthorized","message":"Your request was made with invalid credentials.","code":0,"status":401,"type":"yii\\web\\UnauthorizedHttpException"}`

**Comment by thomasdilts** [comment]
Hi Elias. Nice try, but that auth key is something totally different. Sorry. He needs to log-in to get that kind of authorization key you want.
