### ISSUE TITLE
Profile delete API Not working!

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#99]
this API [Profile delete](https://github.com/thomasdilts/churchsongs/wiki/User-profile-delete) gives this error:

`{
    "name": "Exception",
    "message": "Calling unknown method: common\\models\\User::getAuthAssignments()",
    "code": 0,
    "type": "yii\\base\\UnknownMethodException",
    "file": "/var/www/html/zamar/vendor/yiisoft/yii2/base/Component.php",
    "line": 300,
    "stack-trace": [
        "#0 /var/www/html/zamar/backend/controllers/UserController.php(399): yii\\base\\Component->__call()",
        "#1 /var/www/html/zamar/backend/controllers/UserController.php(363): backend\\controllers\\UserController::deleteUser()",
        "#2 [internal function]: backend\\controllers\\UserController->actionProfiledelete()",
        "#3 /var/www/html/zamar/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()",
        "#4 /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()",
        "#5 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()",
        "#6 /var/www/html/zamar/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction()",
        "#7 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(384): yii\\web\\Application->handleRequest()",
        "#8 /var/www/html/zamar/backend/web/index.php(18): yii\\base\\Application->run()",
        "#9 {main}"
    ]
}`

**Comment by thomasdilts** [comment]
It's a good thing this crashed because this was a rather old function that needed a lot of fixing. Now it works.
